kind: ENC[AES256_GCM,data:Af5HJM2c,iv:qkMsayzKnVjZNY6/g4oeI/uqrCevTR+VTxqRw5hzNsE=,tag:cCSMqWt9sPglRzptjdpnfg==,type:str]
ansible_user: ENC[AES256_GCM,data:uG+Qkg==,iv:xPnAvlB3U1y8YkqVWyE78r1/6Y+fpDutksGSc3h2EbQ=,tag:20BEQ2Zal/Pq2Gd3fKGc9Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:L+9vQoSQc2Zu,iv:arO7diiMNOeYfwYICCo1NCgaIuQzDbzvQDDpwqilC4A=,tag:wGBxVIbiy+dYD7HR4wrfXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN2pXL0xwSWgwa0t2dmcz
            YW5lbG1WQXRtdEx2M0N3b1JDUjN3VzFWR0JVCkRFdXcrcm5zUmtvQVdwOHRGNk1B
            UmcwYzlibi9DcjNISXY3dHRJWkRsVzQKLS0tIHZ5RUpmRlBJclVqa2NTSjZ6M1Y4
            akEyNjJBTGFqZFpIL0s4a1lPODVCcEUKJd+ht3V/uu7hDcQTCJS3G7Z/dQPk6T+W
            ehQrvvDNH7EBfP/H2+oxEca0aiCQqkMHCVdI792zg4TDVCjlQLDLNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T01:04:13Z"
    mac: ENC[AES256_GCM,data:4dTDhUioeNZA+1ntXqsN6RzswwArf6IvxzMJxA/2HKtm8rKPti+8zpr4O0hZ/EdwfLd+RBgwx72O4Tqn0mbFcs0lR/XuBMJGegHAF6g0aiFZThfoOc/4RLkuu0DI0qDOAoIiw/X8O/nKn2lekJDZB8az1yqM5cafGiVssRfSaBg=,iv:jybiZiQFTMnmg9JUfkGFleVrrbGDwE5gQzcw9LbCwtA=,tag:MyiektpAqHPjSzJ3NjQvHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
