apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:5rvJK9OjWjbbU29++Dz+mBMSB8bqzE1+2kgWkCaNw0yGneUVtRLT8M0YP7fEWvywDVvP3ipX5SzOJs3V,iv:t+PT5y6+sA6OKnD4PzP80Mp4i+QRclaOardxX2UtL9U=,tag:h7IABDOhpD0gutKRebEbCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T3Y2ZTdvbWh5R2lQMTgr
            ZnBsZVFNM05GZUNHc3BUcWxLMVNsK1MwMkVzCjRCSVNjT2tNTGk4WWFXam0wQXlE
            MnE5cEthZ2Y4YWNJZjh0aVBacS9hU2sKLS0tIGc4QVhTempDeStlQ1RBMG1PVUZO
            VndvWCtzV3Rjb3ZoNmRIejMvenE3VjAKBSr/09jlYPvpvwH4Qk8sbf8KOKiePmaF
            cebN6LeFepvbokgKty0bKCtUayuv29KewS+ipT2c2D6UBjIt2gdZZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T01:04:13Z"
    mac: ENC[AES256_GCM,data:RyZ2AyR+ChZ/tLK53Txgic4NV1JgTv1mtOkAoSjnCJoKw57xQkzi9Esu5GEYl6Lm+AWRHWAcjsBk22aIStw+/KmGft6ADj8FLFYIrBzQk5zML1v6PkSQKJSyyZNoo8K1S+Mh1pyX8KzWTJuJDqfXvJ5r5847uHs8UUGWuLdVulo=,iv:l7q0SjgTYGQnJPJD+VhMzzqr2Koyx6afx0WuVva+ts4=,tag:raeZu9dIQfo3W+ZThFK+Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
